---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/otelcol"
    ignore:
      - dependency-name: "*"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
