---
name: Validate otelcol

"on":
  workflow_call:

jobs:
  verify-otelcol-code:
    name: Check if the code of otelcol can be built and config is valid
    permissions:
      contents: read
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00  # v6.0.0
        with:
          go-version: '^1.24.0'
      - name: Build otelcol
        run: go build -o otelcol .
        working-directory: otelcol
      - name: Validate otelcol-config.yaml
        run: ./otelcol/otelcol validate --config otelcol-config.yaml
        env:
          MACKEREL_APIKEY: dummy
